name: main

on:
  push:
    tags:
      - v*

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest tag
        id: get_tag
        run: echo "{tag}={$(git describe --tags)}" >> $GITHUB_OUTPUT

      - name: Update README.md
        run: |
          sed -i "s#<version>.*</version>#<version>${{ steps.get_tag.outputs.tag }}</version>#g" README.md

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "oiltea"
          git config --global user.email "oiltea@qq.com"
          git add README.md
          git commit -m "Update version in README.md"
          git push origin HEAD:main